# tests/formula_review.R -----------------------------------------------------
# Human review of every GAM formula the pipeline will fit, before it fits any.
#
#   Rscript tests/formula_review.R
#
# Writes out/formula_review.md (readable) and out/formula_terms.csv (sortable),
# and prints a condensed version to the console.
#
# DATA-FREE. It opens no parquet and reads no rows — every formula is determined
# by config/config.yml and config/pairing.csv alone, which is the property that
# makes MIMIC-test and eICU provably the same code path. If this script ever
# needs data to run, something has leaked into the formula builder.
# ----------------------------------------------------------------------------

for (f in list.files("R", pattern = "\\.R$", full.names = TRUE)) source(f)

cfg <- load_config("config/config.yml")
tm  <- formula_terms(cfg)
ft  <- formula_table(cfg)

out_dir <- "out"
if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
md <- character(0)
add <- function(...) md <<- c(md, sprintf(...))

# --- header -----------------------------------------------------------------
add("# GAM formula review")
add("")
add("Generated by `tests/formula_review.R` from `config/config.yml` +")
add("`config/pairing.csv`. No data is read. Regenerate after any config change.")
add("")
add("- **%d signals x 2 models = %d formulas**, %d-%d terms",
    length(cfg$signals), nrow(ft), min(ft$n_terms), max(ft$n_terms))
add("- `meas` and `full` are identical for the %d unpaired control signals, which have",
    sum(ft$n_paired[ft$model == "meas"] == 0))
add("  no cognate intervention. Expected, not a bug — they are the internal contrast.")
add("- Basis `%s`, k = %d throughout (`config/bam`). `bs = \"ts\"` penalises the null",
    cfg$bam$smooth_basis, cfg$bam$k)
add("  space too, so a useless term shrinks to zero rather than to a straight line.")
add("")

# --- what governs what ------------------------------------------------------
add("## The three selection rules")
add("")
add("| Rule | Governed by | Effect |")
add("|---|---|---|")
add("| Level term | `excursion_side` (pairing.csv) | low -> `q05`, high -> `q95`, undefined -> both. `value_median` always. |")
add("| Propensity term | `signal_tails` (config) | both coordinates unless one is structurally pinned. **Not** `excursion_side`. |")
add("| Trajectory term | `signal_class` | `trend` for dense/rate only; sparse signals carry a constant 0 column. |")
add("")
add("`n_obs` appears in no formula: monitoring frequency is site-specific ordering")
add("behaviour and would transport as an artifact. `n` enters only inside `pi_hat`.")
add("")
add("`o_flag` appears in no formula either, as of 2026-08-25. Its levels were")
add("defined relative to the first excursion, so it encoded measurement")
add("information under an intervention name -- and it was the only term belonging")
add("to neither the `meas` nor the `intv` set. Dropping it makes those two sets")
add("partition `full` exactly, which is what turns `L_full - L_intv` into the")
add("conditional LLR rather than an approximation to it. No formula carries a")
add("`by=` smooth any more, so layer 1 has no interaction terms at all.")
add("")

# --- summary table ----------------------------------------------------------
add("## Summary")
add("")
add("| signal | class | side | pi | trend | ivs | meas | intv | full | delta |")
add("|---|---|---|---|---|---|---|---|---|---|")
for (sg in cfg$signals) {
  z <- ft[ft$signal == sg, ]
  nm <- z$n_terms[z$model == "meas"]; nf <- z$n_terms[z$model == "full"]
  ni <- if (any(z$model == "intv")) z$n_terms[z$model == "intv"] else NA_integer_
  tl <- occupiable_tails_of(sg, cfg)
  cls <- signal_class_of(sg, cfg)
  ivs <- interventions_of(sg, cfg)
  has_trend <- cls %in% c("dense", "rate")
  add("| `%s` | %s | %s | %s | %s | %s | %d | %s | %d | %s |",
      sg, cls, excursion_side_of(sg, cfg) %||% "—",
      paste(tl, collapse = "+"),
      if (has_trend) "yes" else "—",
      if (length(ivs)) paste(ivs, collapse = ", ") else "—",
      nm, if (is.na(ni)) "—" else sprintf("%d", ni),
      nf, if (nf > nm) sprintf("+%d", nf - nm) else "same")
}
add("")

# --- per-signal detail ------------------------------------------------------
add("## Per-signal detail")
add("")
fmt_rows <- function(d) {
  for (i in seq_len(nrow(d))) {
    add("    %2d  %-46s %-14s %s", d$idx[i], d$term[i], d$source[i],
        if (is.na(d$intervention[i])) "" else paste0("<- ", d$intervention[i]))
  }
}
for (sg in cfg$signals) {
  ivs <- interventions_of(sg, cfg)
  add("### `%s`", sg)
  add("")
  add("%s | side `%s` | pi `%s`%s", signal_class_of(sg, cfg),
      excursion_side_of(sg, cfg) %||% "—",
      paste(occupiable_tails_of(sg, cfg), collapse = "+"),
      if (length(ivs)) paste0(" | interventions: `", paste(ivs, collapse = "`, `"), "`")
      else " | **unpaired control**")
  if (!"high" %in% occupiable_tails_of(sg, cfg)) {
    add("")
    add("> `pi_plus` excluded: `k_high == 0` on every stay (reference ceiling), so it")
    add("> would reduce to a monotone function of `n_obs` and separate no patients.")
  }
  add("")
  m <- tm[tm$signal == sg & tm$model == "meas", ]
  add("```")
  add("meas  (%d terms)", nrow(m))
  fmt_rows(m)
  iv <- tm[tm$signal == sg & tm$model == "intv", ]
  if (nrow(iv)) {
    add("")
    add("intv  (%d terms)", nrow(iv))
    fmt_rows(iv)
  } else {
    add("")
    add("intv  does not exist (unpaired: L_intv = 0 by construction, assigned)")
  }
  fl <- tm[tm$signal == sg & tm$model == "full", ]
  if (nrow(fl) == nrow(m)) {
    add("")
    add("full  identical to meas (no cognate intervention)")
  } else {
    add("")
    add("full  (%d terms) = meas + intv, exactly", nrow(fl))
  }
  add("```")
  add("")
}

# --- cross-checks -----------------------------------------------------------
# Assertions a reviewer would otherwise have to make by eye over 50 formulas.
add("## Cross-checks")
add("")
checks <- list()
chk <- function(label, cond, note = "") {
  checks[[length(checks) + 1L]] <<-
    data.frame(check = label, pass = isTRUE(cond), note = note, stringsAsFactors = FALSE)
}

chk("every term classifies", !any(tm$source == "UNCLASSIFIED"),
    paste(unique(tm$term[tm$source == "UNCLASSIFIED"]), collapse = ", "))
chk("no n_obs term", !any(grepl("^ILLEGAL\\(n_obs", tm$source)))
chk("no pi_mid term", !any(grepl("^ILLEGAL\\(pi_mid", tm$source)))
chk("no dx_/qc_ variable", !any(grepl(FORBIDDEN_PREFIX, tm$variable)))
# `value_median` is gated by config `level_terms_include_median` (false as of
# 2026-08-27): it was the hub of the concurvity and dropping it took the worst
# single-term bootstrap SD on creatinine from 0.5486 to 0.1617, at a cost of
# 0.000-0.002 deviance explained. The assertion is that the builder FOLLOWS the
# declaration, not that the term is present.
chk("value_median follows level_terms_include_median",
    all(vapply(cfg[["signals"]], function(sg)
      ("value_median" %in% tm$variable[tm$signal == sg & tm$model != "intv"]) ==
        isTRUE(cfg[["level_terms_include_median"]]), logical(1))))
# `magnitude` is the source when `magnitude_conditional` replaces the raw term
# with its conditional version; the flag being tested is about whether a
# magnitude term is PRESENT, not which of the two names it wears.
LEVEL_SOURCES <- c("level", "magnitude")
chk("level terms follow both include flags", {
  want <- isTRUE(cfg[["level_terms_include_median"]]) ||
          isTRUE(cfg[["level_terms_include_extreme"]] %||% TRUE)
  all(tapply(tm$source[tm$model != "intv"],
             paste(tm$signal, tm$model)[tm$model != "intv"],
             function(v) any(LEVEL_SOURCES %in% v) == want))
})
# A signal may carry the raw magnitude term or its conditional replacement,
# never both: the delta is standardised against exactly what the raw term
# carries, so entering both would re-admit the collinearity it removes.
chk("no signal carries both a raw and a conditional magnitude term",
    all(vapply(cfg$signals, function(sg) {
      v <- tm$source[tm$signal == sg & tm$model != "intv"]
      !("level" %in% v && "magnitude" %in% v)
    }, logical(1))))
chk("magnitude terms appear exactly where magnitude_conditional is on",
    all(vapply(cfg$signals, function(sg) {
      v <- tm$source[tm$signal == sg & tm$model != "intv"]
      ("magnitude" %in% v) == (magnitude_conditional_for(sg, cfg) &&
                               isTRUE(cfg[["level_terms_include_extreme"]] %||% TRUE))
    }, logical(1))))
# lambda replaces the second intensity coordinate; the exposure term stays.
chk("lambda appears exactly where lambda_spec_of says it should",
    all(vapply(cfg$signals, function(sg) {
      v <- tm$variable[tm$signal == sg & tm$model == "full"]
      all(vapply(interventions_of(sg, cfg), function(iv) {
        ls <- lambda_spec_of(iv, cfg)
        has <- paste0(iv, "__lambda") %in% v
        raw <- paste0(iv, "__", if (is.null(ls)) "" else ls$accumulation) %in% v
        if (is.null(ls)) !has else (has && !raw)
      }, logical(1)))
    }, logical(1))))
chk("no measurement term in any intv formula",
    !any(tm$source[tm$model == "intv"] %in%
           c("level", "magnitude", "propensity", "trajectory")))
chk("exactly one trend term where present",
    all(tapply(tm$variable == "trend", paste(tm$signal, tm$model), sum) <= 1L))
chk("no o_flag term anywhere", !any(grepl("^ILLEGAL\\(o_flag", tm$source)) &&
      !any(tm$variable == "o_flag"))
chk("no by= smooth anywhere", all(is.na(tm$by)))
# The partition is the load-bearing property: L_cond = L_full - L_intv is the
# conditional LLR only if meas and intv are disjoint and together exactly full.
chk("meas and intv term sets are disjoint",
    all(vapply(cfg$signals, function(sg) {
      if (!length(interventions_of(sg, cfg))) return(TRUE)
      !length(intersect(tm$term[tm$signal == sg & tm$model == "meas"],
                        tm$term[tm$signal == sg & tm$model == "intv"]))
    }, logical(1))))
chk("meas union intv == full, exactly",
    all(vapply(cfg$signals, function(sg) {
      if (!length(interventions_of(sg, cfg))) return(TRUE)
      setequal(c(tm$term[tm$signal == sg & tm$model == "meas"],
                 tm$term[tm$signal == sg & tm$model == "intv"]),
               tm$term[tm$signal == sg & tm$model == "full"])
    }, logical(1))))
chk("intv models carry only intervention terms",
    all(tm$source[tm$model == "intv"] == "intervention"))
chk("intv exists exactly for the paired signals",
    setequal(unique(tm$signal[tm$model == "intv"]),
             cfg$signals[vapply(cfg$signals, function(sg)
               length(interventions_of(sg, cfg)) > 0L, logical(1))]))
chk("every smooth carries bs and k",
    all(!is.na(tm$basis[tm$kind == "smooth"]) & !is.na(tm$k[tm$kind == "smooth"])))
chk("basis matches config", all(tm$basis[tm$kind == "smooth"] == cfg$bam$smooth_basis))
# k is per covariate, not global: 13 of the smooth covariates are discrete
# enough that the default basis is infeasible. Every emitted k must equal what
# smooth_k_of() resolves for that (signal, variable) — the assertion is that the
# builder used the declaration, not that every k is the same number.
sm_rows <- which(tm$kind == "smooth")
chk("every k matches smooth_k_of()",
    all(vapply(sm_rows, function(i)
      as.integer(tm$k[i]) == smooth_k_of(tm$signal[i], tm$variable[i], cfg),
      logical(1))))
chk("a reduced k only ever reduces",
    all(as.integer(tm$k[sm_rows]) <= cfg$bam$k))
chk("the same covariate gets the same k in every model it appears in",
    all(vapply(split(seq_along(tm$k)[sm_rows],
                     paste(tm$signal[sm_rows], tm$variable[sm_rows])),
               function(ix) length(unique(tm$k[ix])) == 1L, logical(1))))
chk("intervention terms name a paired intervention",
    all(vapply(which(!is.na(tm$intervention)), function(i)
      tm$intervention[i] %in% interventions_of(tm$signal[i], cfg), logical(1))))
chk("meas models carry no intervention term",
    !any(!is.na(tm$intervention) & tm$model == "meas"))
chk("shape-appropriate intervention variables", all(vapply(which(!is.na(tm$intervention)), function(i) {
  v <- sub("^.*__", "", tm$variable[i]); sh <- unlist(cfg$intervention_shape)[[tm$intervention[i]]]
  if (v == "exposure_frac") return(sh == "state")
  if (v %in% c("n_hours", "total_amount")) return(sh == "event")
  if (v %in% c("n_agents", "max_concurrent_agents"))
    return(tm$intervention[i] %in% unlist(cfg$interventions_with_agent_counts))
  TRUE
}, logical(1))))
chk("peak_intensity never modelled", !any(grepl("peak_intensity", tm$variable)))
chk("required_columns matches the term variables",
    all(vapply(cfg$signals, function(sg) all(vapply(models_of(sg, cfg), function(md) {
      f <- build_formula(sg, md, cfg)
      setequal(setdiff(required_columns(f), all.vars(f)[1]),
               unique(tm$variable[tm$signal == sg & tm$model == md]))
    }, logical(1))), logical(1))))

ck <- do.call(rbind, checks)
add("| check | result | note |")
add("|---|---|---|")
for (i in seq_len(nrow(ck))) {
  add("| %s | %s | %s |", ck$check[i], if (ck$pass[i]) "pass" else "**FAIL**", ck$note[i])
}
add("")

# --- write ------------------------------------------------------------------
writeLines(md, file.path(out_dir, "formula_review.md"))
utils::write.csv(tm, file.path(out_dir, "formula_terms.csv"), row.names = FALSE)

cat(sprintf("wrote %s  (%d lines)\n", file.path(out_dir, "formula_review.md"), length(md)))
cat(sprintf("wrote %s  (%d rows)\n\n", file.path(out_dir, "formula_terms.csv"), nrow(tm)))

cat("term counts by source:\n")
print(table(tm$source, tm$model))
cat("\ncross-checks:\n")
for (i in seq_len(nrow(ck))) {
  cat(sprintf("  [%s] %-48s %s\n", if (ck$pass[i]) "ok" else "FAIL", ck$check[i], ck$note[i]))
}
cat(sprintf("\n%d checks, %d failed\n", nrow(ck), sum(!ck$pass)))
if (any(!ck$pass)) quit(status = 1L)
