-- GENERATED by sql/eicu_demo/make_demo_sql.py from sql/eicu/v2_01b_cohort_attrition_eicu.sql.
-- Identical to the source except that
--   physionet-data.eicu_crd.<t>  -> physionet-data.eicu_crd_demo.<t>  (source, ODbL v1.0)
--   eicu-ext.eicu_ext_data.<t>   -> eicu-ext.eicu_ext_data.<t>_demo   (target)
-- Do not edit by hand.
-- v2_01b_cohort_attrition_eicu.sql
-- Attrition ladder for the eICU cohort, rebuilt against the filter chain of
-- v2_01_cohort_eicu.sql (check C4 of that file). The CTE `base` is copied
-- from the cohort query so that the ladder counts exactly what the cohort
-- query keeps; if the cohort query changes, change `base` here too.
--
-- Steps are cumulative in the order the cohort query applies them. The last
-- row must equal COUNT(*) of `eicu-ext.eicu_ext_data.v2_cohort_eicu_demo` (95,507
-- at the run of record); the query asserts this in `matches_cohort_table`.
--
-- Output: one row. Run of record: sql/eicu/eicu_attrition_20260919.csv
-- (matches_cohort_table = true, s8_final = 95,507), beside the MIMIC-IV
-- ladder sql/mimiciv/01_cohort_attrition_table.csv.

WITH base AS (
  SELECT
    p.patientunitstayid,
    p.uniquepid,
    p.gender,
    p.hospitaldischargestatus,
    p.hospitaldischargeoffset,
    p.unitdischargeoffset,
    CASE WHEN TRIM(p.age) = '> 89' THEN 90
         ELSE SAFE_CAST(p.age AS INT64) END      AS age_years,
    ROW_NUMBER() OVER (
      PARTITION BY p.uniquepid
      ORDER BY p.hospitaldischargeyear,
               p.patienthealthsystemstayid,
               p.unitvisitnumber,
               p.patientunitstayid
    ) AS rn
  FROM `physionet-data.eicu_crd_demo.patient` p
),
flags AS (
  SELECT
    rn = 1                                                        AS f1_first_stay,
    age_years >= 18                                               AS f2_adult,
    hospitaldischargestatus IN ('Alive', 'Expired')               AS f3_status_known,
    hospitaldischargeoffset IS NOT NULL
      AND unitdischargeoffset IS NOT NULL                         AS f4_offsets_present,
    unitdischargeoffset >= 1440                                   AS f5_icu_los_24h,
    hospitaldischargeoffset >= 1440                               AS f6_hosp_24h,
    NOT (hospitaldischargestatus = 'Expired'
         AND hospitaldischargeoffset < 1440)                      AS f7_no_pre_landmark_death,
    gender IN ('Female', 'Male')                                  AS f8_sex_recorded
  FROM base
),
ladder AS (
  SELECT
    COUNT(*)                                                                                   AS s0_all_unit_stays,
    COUNTIF(f1_first_stay)                                                                     AS s1_first_stay_per_patient,
    COUNTIF(f1_first_stay AND f2_adult)                                                        AS s2_adult,
    COUNTIF(f1_first_stay AND f2_adult AND f3_status_known)                                    AS s3_outcome_known,
    COUNTIF(f1_first_stay AND f2_adult AND f3_status_known AND f4_offsets_present)             AS s4_offsets_present,
    COUNTIF(f1_first_stay AND f2_adult AND f3_status_known AND f4_offsets_present
            AND f5_icu_los_24h)                                                                AS s5_icu_los_24h,
    COUNTIF(f1_first_stay AND f2_adult AND f3_status_known AND f4_offsets_present
            AND f5_icu_los_24h AND f6_hosp_24h)                                                AS s6_hosp_24h,
    COUNTIF(f1_first_stay AND f2_adult AND f3_status_known AND f4_offsets_present
            AND f5_icu_los_24h AND f6_hosp_24h AND f7_no_pre_landmark_death)                   AS s7_no_pre_landmark_death,
    COUNTIF(f1_first_stay AND f2_adult AND f3_status_known AND f4_offsets_present
            AND f5_icu_los_24h AND f6_hosp_24h AND f7_no_pre_landmark_death
            AND f8_sex_recorded)                                                               AS s8_final
  FROM flags
)
SELECT
  l.*,
  (SELECT COUNT(*) FROM `eicu-ext.eicu_ext_data.v2_cohort_eicu_demo`) AS n_cohort_table,
  l.s8_final = (SELECT COUNT(*) FROM `eicu-ext.eicu_ext_data.v2_cohort_eicu_demo`) AS matches_cohort_table
FROM ladder l;
